# Generated by Django 2.1.2 on 2018-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientProxy',
            fields=[
            ],
            options={
                'ordering': ('description',),
                'proxy': True,
                'indexes': [],
            },
            bases=('firms.ingredient',),
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('description',)},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Ингредиенты Описание'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='description',
            field=models.TextField(verbose_name='Инструкции Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Рецепт'),
        ),
    ]
