# Generated by Django 2.1.2 on 2018-10-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firms', '0003_auto_20181019_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngredientProxy',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='instruction',
        ),
        migrations.CreateModel(
            name='IngredientProxy',
            fields=[
                ('ingredient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='firms.Ingredient')),
            ],
            bases=('firms.ingredient',),
        ),
    ]
